# Default Configuration for DxGPT Evaluation Framework

# General settings
general:
  output_dir: "src/results"
  log_level: "INFO"
  save_intermediate_results: true

# Evaluator configurations
evaluators:
  semantic:
    enabled: true
    config:
      batch_size: 5
      n_diagnoses: 5
      llm_model: "gpt-4o"
      temperature: 0.3
      prompt_path: "src/dxgpt-prompt/dxgpt-prompt.txt"
      
  severity:
    enabled: false  # Not yet implemented
    config:
      severity_mapping_file: null
      weight_by_severity: true
      critical_boost: 2.0
    
# Visualization settings
visualizations:
  enabled: true
  output_format: ["png"]
  
  # Visualizations for semantic evaluator
  semantic:
    - type: "score_distribution"
      enabled: true
    - type: "confusion_matrix"
      enabled: true
    - type: "top_errors"
      enabled: true
      
  # Visualizations for combined evaluators
  combined:
    - type: "2d_scatter"
      enabled: false  # Enable when severity is implemented
      x_axis: "semantic_score"
      y_axis: "severity_score"
      
# Experiment tracking
experiment:
  track_git_status: true
  save_config_snapshot: true
  compress_results: false